package competicion;


import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fran
 */
public class encurso2 extends javax.swing.JFrame {

    Competicion competicion;
    
    DefaultTableModel modeloTabPartidos = new DefaultTableModel()
    {
        @Override
        public boolean isCellEditable(int fil, int col)
        {
            return false;
        }
    };
    
    public encurso2(Competicion c) {
        competicion = c;
        tabPartidos = new JTable(modeloTabPartidos);
        initComponents();
        dibujaTabPartidos();
        rellenarTabPartidos();
    }

    private void dibujaTabPartidos()
    {
        tabPartidos.setModel(modeloTabPartidos);
        String[] columnasTabla = {"Local","","","Visitante"};
        modeloTabPartidos.setColumnIdentifiers(columnasTabla);
        
        // Para no permitir el redimensionamiento de las columnas con el ratón
        tabPartidos.getTableHeader().setResizingAllowed(false);
        
        // Así se fija el ancho de las columnas
        tabPartidos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabPartidos.getColumnModel().getColumn(1).setPreferredWidth(20);
        tabPartidos.getColumnModel().getColumn(2).setPreferredWidth(20);
        tabPartidos.getColumnModel().getColumn(3).setPreferredWidth(50);
    }
    
    public void rellenarTabPartidos()
    {
        Object[] columna = new Object[4];
        
        for(int i = 0; i < competicion.partidos.size(); i++)
        {
            columna[0] = competicion.partidos.get(i).getLocal();
            columna[1] = competicion.partidos.get(i).getGolesL();
            columna[2] = competicion.partidos.get(i).getGolesV();
            columna[3] = competicion.partidos.get(i).getVisitante();
            modeloTabPartidos.addRow(columna);
        }
    }
    
    public void vaciarTabPartidos()
    {
        while (modeloTabPartidos.getRowCount() > 0)
            modeloTabPartidos.removeRow(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabPartidos = new javax.swing.JTable();
        botonVerCuadro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPartidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabPartidos);

        botonVerCuadro.setText("Ver cuadro");
        botonVerCuadro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerCuadroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(botonVerCuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(botonVerCuadro)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPartidosMouseClicked
        int index = tabPartidos.getSelectedRow();
        
        String nL = tabPartidos.getModel().getValueAt(index, 0).toString();
        String nV = tabPartidos.getModel().getValueAt(index, 3).toString();
        
        String gL = JOptionPane.showInputDialog("Introduce goles local: ");
        String gV = JOptionPane.showInputDialog("Introduce goles visitante: ");
        
        competicion.partidos.get(index).setGolesL(gL);
        competicion.partidos.get(index).setGolesV(gV);
        
        boolean encontrado1 = false, encontrado2 = false;
        int i = 0;
        int indice1 = -1, indice2 = -1;
        
        while((!encontrado1 || !encontrado2) && i < competicion.jugadores.size())
        {
            if(nL == competicion.jugadores.get(i).getNombre())
            {
                encontrado1 = true;
                indice1 = i;
            }
            
            if(nV == competicion.jugadores.get(i).getNombre())
            {
                encontrado2 = true;
                indice2 = i;
            }
            
            i++;
        }
        
        if(Integer.parseInt(gL) > Integer.parseInt(gV))
        {
            competicion.partidos.get(index).setGanador(competicion.jugadores.get(indice1).getNombre());
            competicion.jugadores.remove(indice2);
        }
        else
        {
            competicion.partidos.get(index).setGanador(competicion.jugadores.get(indice2).getNombre());
            competicion.jugadores.remove(indice1);
        }
        
        tabPartidos.getModel().setValueAt(gL, index, 1);
        tabPartidos.getModel().setValueAt(gV, index, 2);
        
        if(competicion.jugadores.size() != 1)
        {    
            boolean vacio = false;
            int j = 0;
            while(!vacio && (j < competicion.partidos.size()))
            {
                if(competicion.partidos.get(j).getGolesL().equals(""))
                    vacio = true;
                else
                    j++;
            }

            if(!vacio)
            {
                competicion.GenerarPartidos(competicion.jugadores);
                vaciarTabPartidos();
                rellenarTabPartidos();
            }
        }
    }//GEN-LAST:event_tabPartidosMouseClicked

    private void botonVerCuadroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerCuadroActionPerformed
        VerCuadro vc = new VerCuadro(competicion);
        vc.setVisible(true);
    }//GEN-LAST:event_botonVerCuadroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVerCuadro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabPartidos;
    // End of variables declaration//GEN-END:variables
}
